trigger:
  branches:
    include:
      - main # or the branch you want to trigger the pipeline

pool:
  name: 'Azure Pipelines'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x.x' # Use the correct .NET 8 version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore
    dotnet build --configuration Release
    dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Build and Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azureapp'
    appType: 'webApp'
    WebAppName: 'freshxapi'
    deployToSlotOrASE: true
    ResourceGroupName: 'DATN-FreshX'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
