name: Build and deploy ASP.Net Core app to Azure Web App - freshxapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore


      - name: Build with dotnet
        run: |  
          dotnet build --configuration Release
      
         # Publish project to folder
      - name: Publish project
        run: dotnet publish -c Release -o ./publish

           # Tạo file .env trong thư mục publish
      - name: Create .env file
        run: |
          echo ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }} >> ./publish/.env
          echo ENCRYPTION_SALT=${{ secrets.ENCRYPTION_SALT }} >> ./publish/.env



        # Deploy to Azure Web App
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: true  # Bật upload file ẩn như .env

      # Kiểm tra xem file .env có tồn tại trong thư mục publish không
      - name: Verify .env file
        run: |
          dir ./publish
          
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: true  # Bật tải xuống file ẩn như .env
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66BAB843D6E24E99A7934132BCA2112A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4850701E6B29451C971C9DD569C78893 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45D212DBA9B142D3B709A40190FA8DC1 }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'freshxapi'
          slot-name: 'Production'
          package: .