name: Build and deploy ASP.Net Core app to Azure Web App - freshxapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build the app
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish the app to the ./publish folder
      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish

      # Create .env file inside ./publish directory
      - name: Create .env file
        run: |
          echo ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }} >> ./publish/.env
          echo ENCRYPTION_SALT=${{ secrets.ENCRYPTION_SALT }} >> ./publish/.env

      # Upload the artifact to use in the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: true  # Ensure hidden files like .env are uploaded


# Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the artifact that was created during the build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: true  # Ensure .env is downloaded

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EEF0B67F41F9433B94241D5F57D3CD2A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45D19416E22C4DF7BA0C362726240AAF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_804885B6CFE64AB789C965CFFF0C74DD }}

      # Deploy the app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'freshxapi'
          package: .
