name: Build and deploy ASP.Net Core app to Azure Web App - freshxapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Build the app
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Publish the app to the ./publish folder
      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish

      # Create .env file inside ./publish directory
      - name: Create .env file
        run: |
          echo ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }} >> ./publish/.env
          echo ENCRYPTION_SALT=${{ secrets.ENCRYPTION_SALT }} >> ./publish/.env

      # Upload the artifact to use in the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: true  # Ensure hidden files like .env are uploaded


# Deploy job
 